dl command removed, behaviour accessed by default

diff --git a/qdl b/qdl
--- a/qdl
+++ b/qdl
@@ -5,12 +5,12 @@
 ########## HELPER FUNCTIONS ###########
 usage() {
 	echo 'qdl
-	help
-	login
-	latest [n]
-	search <str>
-	eps <series_id>
-	dl [-d <outputdir>] <ep_id>+'
+  -h | --help | help
+  login
+  latest [n]
+  search <str>
+  eps <series_id>
+  [-d <outputdir>] <ep_id>+'
 }
 
 
@@ -20,7 +20,7 @@ missing_arg_error() {
 
 
 cookiejar_assert_ok() {
-	[[ ! -r "${cookiejar}" ]] && { echo "Error: cookiejar ${cookiejar} does not exist or cannot be read by current user. This is expected if you have never logged in." >&2; exit 1; }
+	[[ ! -r "${cookiejar}" ]] && { echo "Error: ${cookiejar} does not exist or cannot be read by current user. This is expected if you have never logged in." >&2; exit 1; }
 }
 
 
@@ -32,6 +32,9 @@ json_status_assert_ok() {
 http_status_assert_ok() {
 	local status="$(sed -n '1s/HTTP\/1.1 \(...\).*/\1/p' <<< "$1")"
 	case "${status}" in
+		"302")
+			# success
+			;;
 		"404")
 			echo "Error: file not found. Please check ID is correct." >&2
 			exit 1
@@ -40,11 +43,8 @@ http_status_assert_ok() {
 			echo "Error: unauthorized. Your session probably expired. Try logging in again." >&2
 			exit 1
 			;;
-		"302")
-			# success
-			;;
 		*)
-			echo "Error: ${status}." >&2
+			echo "Error: HTTPS request returned status code ${status}." >&2
 			exit 1
 			;;
 	esac
@@ -93,11 +93,11 @@ cookiejar="${user_data_prefix}/quedia-dl/cookiejar"
 
 while [[ -n "$1" ]]; do
 	case "$1" in
-		'help')
+		-h|--help|help)
 			usage
-			exit
+			exit 0
 			;;
-		'login')
+		login)
 			read -p "Username: " -r username
 			read -p "Password: " -s -r password
 			echo
@@ -111,7 +111,7 @@ while [[ -n "$1" ]]; do
 				exit 1
 			fi
 			;;
-		'latest')
+		latest)
 			cookiejar_assert_ok
 			latest_payload='{"limit":0}'
 			[[ -n "$2" ]] && { number_assert_ok "$2"; latest_payload="{\"limit\":$2}"; shift; }
@@ -119,7 +119,7 @@ while [[ -n "$1" ]]; do
 			json_status_assert_ok "${json_reply}"
 			jq_print_get_series "${json_reply}"
 			;;
-		'search')
+		search)
 			if [[ -n "$2" ]]; then
 				cookiejar_assert_ok
 				search_payload="$(jq -n -aRc --arg str "$2" '{search: $str}')"
@@ -131,7 +131,7 @@ while [[ -n "$1" ]]; do
 				missing_arg_error 'search'
 			fi
 			;;
-		'eps')
+		eps)
 			if [[ -n "$2" ]]; then
 				cookiejar_assert_ok
 				number_assert_ok "$2"
@@ -143,14 +143,14 @@ while [[ -n "$1" ]]; do
 				missing_arg_error 'eps'
 			fi
 			;;
-		'dl')
+		*)
 			outputdir='.'
 			if [[ "$2" == '-d' ]]; then
 				[[ ! -n "$3" ]] && missing_arg_error '-d'
 				outputdir="$3"
 				shift; shift
 			fi
-			[[ ! -n "$2" ]] && missing_arg_error 'dl'
+			[[ ! -n "$2" ]] && { usage; exit 1; }
 			cookiejar_assert_ok
 			while [[ -n "$2" ]]; do
 				reply="$(curl -si -b "${cookiejar}" "https://quedia.tv/api/storage/get_download_link/$2")"
@@ -166,10 +166,6 @@ while [[ -n "$1" ]]; do
 				fi
 				shift
 			done
-			;;
-		*)
-			usage
-			exit 1
 			;;
 	esac
 	shift
