added latest

diff --git a/quedia-dl b/quedia-dl
--- a/quedia-dl
+++ b/quedia-dl
@@ -1,4 +1,5 @@
 #!/bin/bash
+# Basic interface to https://quedia.tv
 
 
 ########## HELPER FUNCTIONS ###########
@@ -6,6 +7,7 @@ usage() {
 	echo 'quedia-dl
 	help
 	login
+	latest [n]
 	search <str>
 	eps <series_id>
 	dl <ep_id>+'
@@ -49,6 +51,13 @@ http_status_assert_ok() {
 }
 
 
+number_assert_ok() {
+	local regex='[[:digit:]]+'
+	[[ ! "$1" =~ $regex ]] && { echo 'Error: argument should be a number.' >&2; exit 1; }
+	[[ "$1" -lt 1 ]] && { echo 'Error: number should be greater than 0.' >&2; exit 1; }
+}
+
+
 quedia_request() {
 	if [[ -n "$2" ]]; then
 		curl -s -H "Accept: application/json" -H "Content-Type: application/json" -b "${cookiejar}" --data-raw "$2" "https://quedia.tv/api/$1"
@@ -60,6 +69,11 @@ quedia_request() {
 
 url_decode() {
 	printf '%b' "${1//%/\\x}"
+}
+
+
+jq_print_get_series() {
+	jq -r '.response[] as $items | ("> " + ($items.id | tostring) + " " + $items.name + ": " + $items.description)' <<< "$1"
 }
 #######################################
 
@@ -88,13 +102,22 @@ while [[ -n "$1" ]]; do
 			read -p "Password: " -s -r password
 			echo
 			login_payload="$(jq -n -aRc --arg username "${username}" --arg "password" "${password}" '{username: $username, password: $password}')"
-			if [[ "$(curl -s -H "Accept: application/json" -H "Content-Type: application/json" -X POST --data-raw "${login_payload}" -c "${cookiejar}" 'https://quedia.tv/api/profile/login' | jq '.status == "ok"')" == 'true' ]]; then
-				echo 'Login successful.'
+			if [[ "$(curl -s -H "Accept: application/json" -H "Content-Type: application/json" --data-raw "${login_payload}" -c "${cookiejar}" 'https://quedia.tv/api/profile/login' | jq '.status == "ok"')" == 'true' ]]; then
+				chmod 800 "${cookiejar}"
+				echo 'Login successful.' >&2
 			else
-				echo 'Error. Please double check your credentials.'
+				echo 'Error. Please double check your credentials.' >&2
 				rm -f "${cookiejar}"
 				exit 1
 			fi
+			;;
+		'latest')
+			cookiejar_assert_ok
+			latest_payload='{"limit":0}'
+			[[ -n "$2" ]] && { number_assert_ok "$2"; latest_payload="{\"limit\":$2}"; shift; }
+			json_reply="$(quedia_request "media/get_series" "${latest_payload}")"
+			json_status_assert_ok "${json_reply}"
+			jq_print_get_series "${json_reply}"
 			;;
 		'search')
 			if [[ -n "$2" ]]; then
@@ -102,22 +125,24 @@ while [[ -n "$1" ]]; do
 				search_payload="$(jq -n -aRc --arg str "$2" '{search: $str}')"
 				json_reply="$(quedia_request "media/get_series" "${search_payload}")"
 				json_status_assert_ok "${json_reply}"
-				jq -r '.response[] as $items | ($items.name + " (ID " + ($items.id | tostring) + "): " + $items.description + "\n")' <<< "${json_reply}"
+				jq_print_get_series "${json_reply}"
+				shift
 			else
 				missing_arg_error 'search'
 			fi
-			shift
 			;;
 		'eps')
 			if [[ -n "$2" ]]; then
 				cookiejar_assert_ok
+				number_assert_ok "$2"
 				json_reply="$(quedia_request "media/get_series" "{\"id\":$2,\"depth\":3}")"
 				json_status_assert_ok
+				echo "${json_reply}"
 				jq -r '.response[].seasons[].episodes[].signatures[] as $items | ($items.uid + " " + $items.filename)' <<< "${json_reply}"
+				shift
 			else
 				missing_arg_error 'eps'
 			fi
-			shift
 			;;
 		'dl')
 			[[ ! -n "$2" ]] && missing_arg_error 'dl'
